erDiagram
    Sys_Parametros {
        varchar par_codigo PK
        varchar par_nombre 
        varchar par_descripcion 
        varchar par_valor 
    }
    Sis_Excepcion {
        int lge_codigo PK
        varchar lge_texto 
        varchar lge_error 
        datetime lge_fecha_act 
    }