USE [db_acd593_sigma]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:          EMILIO FUENTES
-- FECHA CREACION:  11-09-2026
-- DESCRIPTION:     SPRINT 4 - PAUTA REAL SOP-09-R24 CHECK LIST SERVICIOS (HAMBURGO).
-- =============================================
-- Deshabilita el checklist de ejemplo del demo de la App y crea la pauta real
-- SOP-09-R24 con todas sus secciones y campos (equipo x parametro), sobre su
-- version BORRADOR usando los SP de estructura. ES IDEMPOTENTE (reemplaza).
-- =============================================
SET NOCOUNT ON
GO

DECLARE @CLIENTE INT = 1, @USUARIO INT = 9, @PLANTILLA INT, @VERSION INT, @PLANTA INT, @SEC INT, @ITEM INT
SELECT TOP 1 @PLANTA = cin_id FROM [dbo].[Cliente_Instalacion] WHERE cin_cliente=@CLIENTE AND cin_habilitado=1 ORDER BY cin_id

-- 1) Deshabilita el checklist de ejemplo (no se borra: tiene ejecuciones del demo App).
UPDATE [dbo].[Checklist_Plantilla] SET cpl_habilitado=0, cpl_usuario_actualizacion=@USUARIO WHERE cpl_cliente=@CLIENTE AND cpl_codigo=N'CHK-RONDA-MOT'

-- 2) Cabecera de la pauta real (buscar-o-crear por codigo).
SELECT @PLANTILLA = cpl_id FROM [dbo].[Checklist_Plantilla] WHERE cpl_cliente=@CLIENTE AND cpl_codigo=N'SOP-09-R24'
IF @PLANTILLA IS NULL
BEGIN
    EXEC [dbo].[INS_CHECKLIST_PLANTILLA] @ID=@PLANTILLA OUTPUT, @CLIENTE=@CLIENTE, @CLIENTE_INSTALACION=@PLANTA,
         @CHECKLIST_ASIGNACION_TIPO=NULL, @ACTIVO_TIPO=NULL, @CODIGO=N'SOP-09-R24',
         @NOMBRE=N'Check List Servicios (SOP-09-R24)',
         @DESCRIPCION=N'Servicio diario del Departamento de Mantenimiento. Frecuencia: diaria. Version 09.', @USUARIO=@USUARIO
END
ELSE
    UPDATE [dbo].[Checklist_Plantilla] SET cpl_habilitado=1, cpl_usuario_actualizacion=@USUARIO WHERE cpl_id=@PLANTILLA

-- 3) Version BORRADOR y limpieza (reemplazo).
EXEC [dbo].[GET_CHECKLIST_BORRADOR] @PLANTILLA=@PLANTILLA, @USUARIO=@USUARIO, @CREAR=1, @VERSION=@VERSION OUTPUT
EXEC [dbo].[LIMPIAR_CHECKLIST_BORRADOR] @VERSION=@VERSION

-- Seccion: Silos Zeppelin
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-1', @NOMBRE=N'Silos Zeppelin', @ORDEN=1, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-1', @TEXTO=N'Silo 1 - Filtracion aire', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-2', @TEXTO=N'Silo 1 - Filtracion harina', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-3', @TEXTO=N'Silo 1 - Filtros de los secaderos', @TIPO=5, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-4', @TEXTO=N'Silo 1 - Estado de los fuelles', @TIPO=5, @ORDEN=4, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-5', @TEXTO=N'Silo 2 - Filtracion aire', @TIPO=5, @ORDEN=5, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-6', @TEXTO=N'Silo 2 - Filtracion harina', @TIPO=5, @ORDEN=6, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-7', @TEXTO=N'Silo 2 - Filtros de los secaderos', @TIPO=5, @ORDEN=7, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-8', @TEXTO=N'Silo 2 - Estado de los fuelles', @TIPO=5, @ORDEN=8, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-9', @TEXTO=N'Silo 3 - Filtracion aire', @TIPO=5, @ORDEN=9, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-10', @TEXTO=N'Silo 3 - Filtracion harina', @TIPO=5, @ORDEN=10, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-11', @TEXTO=N'Silo 3 - Filtros de los secaderos', @TIPO=5, @ORDEN=11, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-1-12', @TEXTO=N'Silo 3 - Estado de los fuelles', @TIPO=5, @ORDEN=12, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Blowers de harina
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-2', @NOMBRE=N'Blowers de harina', @ORDEN=2, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-1', @TEXTO=N'Blower 1 - Fugas de aire', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-2', @TEXTO=N'Blower 1 - Fugas de aceite', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-3', @TEXTO=N'Blower 1 - Estado de correas', @TIPO=5, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-4', @TEXTO=N'Blower 1 - Presion de trabajo', @TIPO=4, @ORDEN=4, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-5', @TEXTO=N'Blower 1 - Nivel de aceite', @TIPO=5, @ORDEN=5, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-6', @TEXTO=N'Blower 1 - Horometro', @TIPO=3, @ORDEN=6, @UNIDAD=13, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-7', @TEXTO=N'Blower 2 - Fugas de aire', @TIPO=5, @ORDEN=7, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-8', @TEXTO=N'Blower 2 - Fugas de aceite', @TIPO=5, @ORDEN=8, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-9', @TEXTO=N'Blower 2 - Estado de correas', @TIPO=5, @ORDEN=9, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-10', @TEXTO=N'Blower 2 - Presion de trabajo', @TIPO=4, @ORDEN=10, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-11', @TEXTO=N'Blower 2 - Nivel de aceite', @TIPO=5, @ORDEN=11, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-12', @TEXTO=N'Blower 2 - Horometro', @TIPO=3, @ORDEN=12, @UNIDAD=13, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-13', @TEXTO=N'Blower 3 - Fugas de aire', @TIPO=5, @ORDEN=13, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-14', @TEXTO=N'Blower 3 - Fugas de aceite', @TIPO=5, @ORDEN=14, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-15', @TEXTO=N'Blower 3 - Estado de correas', @TIPO=5, @ORDEN=15, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-16', @TEXTO=N'Blower 3 - Presion de trabajo', @TIPO=4, @ORDEN=16, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-17', @TEXTO=N'Blower 3 - Nivel de aceite', @TIPO=5, @ORDEN=17, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-18', @TEXTO=N'Blower 3 - Horometro', @TIPO=3, @ORDEN=18, @UNIDAD=13, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-19', @TEXTO=N'Blower 4 - Fugas de aire', @TIPO=5, @ORDEN=19, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-20', @TEXTO=N'Blower 4 - Fugas de aceite', @TIPO=5, @ORDEN=20, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-21', @TEXTO=N'Blower 4 - Estado de correas', @TIPO=5, @ORDEN=21, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-22', @TEXTO=N'Blower 4 - Presion de trabajo', @TIPO=4, @ORDEN=22, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-23', @TEXTO=N'Blower 4 - Nivel de aceite', @TIPO=5, @ORDEN=23, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-2-24', @TEXTO=N'Blower 4 - Horometro', @TIPO=3, @ORDEN=24, @UNIDAD=13, @USUARIO=@USUARIO

-- Seccion: Gas Lipigas
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-3', @NOMBRE=N'Gas Lipigas', @ORDEN=3, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-3-1', @TEXTO=N'Evaporador 1 - Estado', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-3-2', @TEXTO=N'Evaporador 2 - Estado', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-3-3', @TEXTO=N'Evaporador 3 - Estado', @TIPO=5, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Levadura liquida
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-4', @NOMBRE=N'Levadura liquida', @ORDEN=4, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-4-1', @TEXTO=N'Estanque de levadura - Fallas', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-4-2', @TEXTO=N'Estanque de levadura - Filtracion', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-4-3', @TEXTO=N'Estanque de levadura - T C estanque en uso', @TIPO=4, @ORDEN=3, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-4-4', @TEXTO=N'Estanque de levadura - T C anillo', @TIPO=4, @ORDEN=4, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-4-5', @TEXTO=N'Estanque de levadura - T C estanque almacenamiento', @TIPO=4, @ORDEN=5, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-4-6', @TEXTO=N'Estanque de levadura - Presion', @TIPO=4, @ORDEN=6, @UNIDAD=25, @USUARIO=@USUARIO

-- Seccion: Sala electrica
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-5', @NOMBRE=N'Sala electrica', @ORDEN=5, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-1', @TEXTO=N'Transformador 1 - T C Panel', @TIPO=4, @ORDEN=1, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-2', @TEXTO=N'Transformador 1 - Alarmas', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-3', @TEXTO=N'Transformador 1 - Fallas', @TIPO=5, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-4', @TEXTO=N'Transformador 1 - Orden y limpieza de area', @TIPO=5, @ORDEN=4, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-5', @TEXTO=N'Transformador 2 - T C Panel', @TIPO=4, @ORDEN=5, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-6', @TEXTO=N'Transformador 2 - Alarmas', @TIPO=5, @ORDEN=6, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-7', @TEXTO=N'Transformador 2 - Fallas', @TIPO=5, @ORDEN=7, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-8', @TEXTO=N'Transformador 2 - Orden y limpieza de area', @TIPO=5, @ORDEN=8, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-9', @TEXTO=N'Transformador 3 - T C Panel', @TIPO=4, @ORDEN=9, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-10', @TEXTO=N'Transformador 3 - Alarmas', @TIPO=5, @ORDEN=10, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-11', @TEXTO=N'Transformador 3 - Fallas', @TIPO=5, @ORDEN=11, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-5-12', @TEXTO=N'Transformador 3 - Orden y limpieza de area', @TIPO=5, @ORDEN=12, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Aire comprimido Kaeser
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-6', @NOMBRE=N'Aire comprimido Kaeser', @ORDEN=6, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-1', @TEXTO=N'Compresor 1 - Presion', @TIPO=4, @ORDEN=1, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-2', @TEXTO=N'Compresor 1 - T C', @TIPO=4, @ORDEN=2, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-3', @TEXTO=N'Compresor 1 - Mantenimiento (horas)', @TIPO=3, @ORDEN=3, @UNIDAD=13, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-4', @TEXTO=N'Compresor 1 - Nivel de aceite', @TIPO=5, @ORDEN=4, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-5', @TEXTO=N'Compresor 2 - Presion', @TIPO=4, @ORDEN=5, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-6', @TEXTO=N'Compresor 2 - T C', @TIPO=4, @ORDEN=6, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-7', @TEXTO=N'Compresor 2 - Mantenimiento (horas)', @TIPO=3, @ORDEN=7, @UNIDAD=13, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-8', @TEXTO=N'Compresor 2 - Nivel de aceite', @TIPO=5, @ORDEN=8, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-9', @TEXTO=N'Compresor 3 - Presion', @TIPO=4, @ORDEN=9, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-10', @TEXTO=N'Compresor 3 - T C', @TIPO=4, @ORDEN=10, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-11', @TEXTO=N'Compresor 3 - Mantenimiento (horas)', @TIPO=3, @ORDEN=11, @UNIDAD=13, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-12', @TEXTO=N'Compresor 3 - Nivel de aceite', @TIPO=5, @ORDEN=12, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-13', @TEXTO=N'Secador - Presion', @TIPO=4, @ORDEN=13, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-14', @TEXTO=N'Secador - T C', @TIPO=4, @ORDEN=14, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-15', @TEXTO=N'Secador - Mantenimiento (horas)', @TIPO=3, @ORDEN=15, @UNIDAD=13, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-6-16', @TEXTO=N'Secador - Nivel de aceite', @TIPO=5, @ORDEN=16, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Generadores Perkin-Cummins
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-7', @NOMBRE=N'Generadores Perkin-Cummins', @ORDEN=7, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-1', @TEXTO=N'Perkin - Automatico', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-2', @TEXTO=N'Perkin - Manual', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-3', @TEXTO=N'Perkin - Fallas', @TIPO=5, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-4', @TEXTO=N'Perkin - Nivel de combustible', @TIPO=5, @ORDEN=4, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-5', @TEXTO=N'Perkin - Nivel de aceite', @TIPO=5, @ORDEN=5, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-6', @TEXTO=N'Cummins 2 - Automatico', @TIPO=5, @ORDEN=6, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-7', @TEXTO=N'Cummins 2 - Manual', @TIPO=5, @ORDEN=7, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-8', @TEXTO=N'Cummins 2 - Fallas', @TIPO=5, @ORDEN=8, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-9', @TEXTO=N'Cummins 2 - Nivel de combustible', @TIPO=5, @ORDEN=9, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-10', @TEXTO=N'Cummins 2 - Nivel de aceite', @TIPO=5, @ORDEN=10, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-11', @TEXTO=N'Cummins 3 - Automatico', @TIPO=5, @ORDEN=11, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-12', @TEXTO=N'Cummins 3 - Manual', @TIPO=5, @ORDEN=12, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-13', @TEXTO=N'Cummins 3 - Fallas', @TIPO=5, @ORDEN=13, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-14', @TEXTO=N'Cummins 3 - Nivel de combustible', @TIPO=5, @ORDEN=14, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-15', @TEXTO=N'Cummins 3 - Nivel de aceite', @TIPO=5, @ORDEN=15, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-16', @TEXTO=N'Cummins 4 - Automatico', @TIPO=5, @ORDEN=16, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-17', @TEXTO=N'Cummins 4 - Manual', @TIPO=5, @ORDEN=17, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-18', @TEXTO=N'Cummins 4 - Fallas', @TIPO=5, @ORDEN=18, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-19', @TEXTO=N'Cummins 4 - Nivel de combustible', @TIPO=5, @ORDEN=19, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-7-20', @TEXTO=N'Cummins 4 - Nivel de aceite', @TIPO=5, @ORDEN=20, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Boiler fermentadoras
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-8', @NOMBRE=N'Boiler fermentadoras', @ORDEN=8, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-8-1', @TEXTO=N'Boiler fermentadoras - Presion set', @TIPO=4, @ORDEN=1, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-8-2', @TEXTO=N'Boiler fermentadoras - Presion real', @TIPO=4, @ORDEN=2, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-8-3', @TEXTO=N'Boiler fermentadoras - Temperatura salida', @TIPO=4, @ORDEN=3, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-8-4', @TEXTO=N'Boiler fermentadoras - Temperatura retorno', @TIPO=4, @ORDEN=4, @UNIDAD=17, @USUARIO=@USUARIO

-- Seccion: BB Grundfos boiler fermentadoras
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-9', @NOMBRE=N'BB Grundfos boiler fermentadoras', @ORDEN=9, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-9-1', @TEXTO=N'BB Grundfos #1 - Set point (caudal)', @TIPO=4, @ORDEN=1, @UNIDAD=35, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-9-2', @TEXTO=N'BB Grundfos #1 - Diferencia presion bomba', @TIPO=4, @ORDEN=2, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-9-3', @TEXTO=N'BB Grundfos #1 - Consumo potencia', @TIPO=4, @ORDEN=3, @UNIDAD=21, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-9-4', @TEXTO=N'BB Grundfos #2 - Set point (caudal)', @TIPO=4, @ORDEN=4, @UNIDAD=35, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-9-5', @TEXTO=N'BB Grundfos #2 - Diferencia presion bomba', @TIPO=4, @ORDEN=5, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-9-6', @TEXTO=N'BB Grundfos #2 - Consumo potencia', @TIPO=4, @ORDEN=6, @UNIDAD=21, @USUARIO=@USUARIO

-- Seccion: Boiler manteca
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-10', @NOMBRE=N'Boiler manteca', @ORDEN=10, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-10-1', @TEXTO=N'Boiler manteca - Presion set', @TIPO=4, @ORDEN=1, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-10-2', @TEXTO=N'Boiler manteca - Presion real', @TIPO=4, @ORDEN=2, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-10-3', @TEXTO=N'Boiler manteca - Temperatura salida', @TIPO=4, @ORDEN=3, @UNIDAD=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-10-4', @TEXTO=N'Boiler manteca - Temperatura retorno', @TIPO=4, @ORDEN=4, @UNIDAD=17, @USUARIO=@USUARIO

-- Seccion: BB Grundfos boiler manteca
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-11', @NOMBRE=N'BB Grundfos boiler manteca', @ORDEN=11, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-11-1', @TEXTO=N'BB Grundfos #1 - Set point (caudal)', @TIPO=4, @ORDEN=1, @UNIDAD=35, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-11-2', @TEXTO=N'BB Grundfos #1 - Diferencia presion bomba', @TIPO=4, @ORDEN=2, @UNIDAD=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-11-3', @TEXTO=N'BB Grundfos #1 - Consumo potencia', @TIPO=4, @ORDEN=3, @UNIDAD=21, @USUARIO=@USUARIO

-- Seccion: Filtracion pipping
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-12', @NOMBRE=N'Filtracion pipping', @ORDEN=12, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-12-1', @TEXTO=N'Pipping agua silos', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-12-2', @TEXTO=N'Pipping flexible de harina', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: % Velocidad de operacion Fritsch
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-13', @NOMBRE=N'% Velocidad de operacion Fritsch', @ORDEN=13, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-13-1', @TEXTO=N'L1 - Turno manana', @TIPO=4, @ORDEN=1, @UNIDAD=20, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-13-2', @TEXTO=N'L1 - Turno tarde', @TIPO=4, @ORDEN=2, @UNIDAD=20, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-13-3', @TEXTO=N'L1 - Turno noche', @TIPO=4, @ORDEN=3, @UNIDAD=20, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-13-4', @TEXTO=N'L2 - Turno manana', @TIPO=4, @ORDEN=4, @UNIDAD=20, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-13-5', @TEXTO=N'L2 - Turno tarde', @TIPO=4, @ORDEN=5, @UNIDAD=20, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-13-6', @TEXTO=N'L2 - Turno noche', @TIPO=4, @ORDEN=6, @UNIDAD=20, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-13-7', @TEXTO=N'L3 - Turno manana', @TIPO=4, @ORDEN=7, @UNIDAD=20, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-13-8', @TEXTO=N'L3 - Turno tarde', @TIPO=4, @ORDEN=8, @UNIDAD=20, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-13-9', @TEXTO=N'L3 - Turno noche', @TIPO=4, @ORDEN=9, @UNIDAD=20, @USUARIO=@USUARIO

-- Seccion: Cortes por minuto AMF
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-14', @NOMBRE=N'Cortes por minuto AMF', @ORDEN=14, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-14-1', @TEXTO=N'L4 - Turno manana', @TIPO=3, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-14-2', @TEXTO=N'L4 - Turno tarde', @TIPO=3, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-14-3', @TEXTO=N'L4 - Turno noche', @TIPO=3, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Bombas de agua planta
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-15', @NOMBRE=N'Bombas de agua planta', @ORDEN=15, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-15-1', @TEXTO=N'Bomba 1 (7,5 kW) - Filtracion', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-15-2', @TEXTO=N'Bomba 1 (7,5 kW) - Consumo', @TIPO=4, @ORDEN=2, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-15-3', @TEXTO=N'Bomba 1 (7,5 kW) - Observaciones', @TIPO=2, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-15-4', @TEXTO=N'Bomba 2 (7,5 kW) - Filtracion', @TIPO=5, @ORDEN=4, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-15-5', @TEXTO=N'Bomba 2 (7,5 kW) - Consumo', @TIPO=4, @ORDEN=5, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-15-6', @TEXTO=N'Bomba 2 (7,5 kW) - Observaciones', @TIPO=2, @ORDEN=6, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-15-7', @TEXTO=N'Bomba 3 (7,5 kW) - Filtracion', @TIPO=5, @ORDEN=7, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-15-8', @TEXTO=N'Bomba 3 (7,5 kW) - Consumo', @TIPO=4, @ORDEN=8, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-15-9', @TEXTO=N'Bomba 3 (7,5 kW) - Observaciones', @TIPO=2, @ORDEN=9, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Bomba de pozo profundo
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-16', @NOMBRE=N'Bomba de pozo profundo', @ORDEN=16, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-16-1', @TEXTO=N'Bomba de pozo profundo (15 kW) - Filtracion', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-16-2', @TEXTO=N'Bomba de pozo profundo (15 kW) - Consumo', @TIPO=4, @ORDEN=2, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-16-3', @TEXTO=N'Bomba de pozo profundo (15 kW) - Observaciones', @TIPO=2, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Bombas de agua sumergible
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-17', @NOMBRE=N'Bombas de agua sumergible', @ORDEN=17, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-17-1', @TEXTO=N'Bomba 1 - Filtracion', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-17-2', @TEXTO=N'Bomba 1 - Consumo', @TIPO=4, @ORDEN=2, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-17-3', @TEXTO=N'Bomba 1 - Observaciones', @TIPO=2, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-17-4', @TEXTO=N'Bomba 2 - Filtracion', @TIPO=5, @ORDEN=4, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-17-5', @TEXTO=N'Bomba 2 - Consumo', @TIPO=4, @ORDEN=5, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-17-6', @TEXTO=N'Bomba 2 - Observaciones', @TIPO=2, @ORDEN=6, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-17-7', @TEXTO=N'Bomba 3 - Filtracion', @TIPO=5, @ORDEN=7, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-17-8', @TEXTO=N'Bomba 3 - Consumo', @TIPO=4, @ORDEN=8, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-17-9', @TEXTO=N'Bomba 3 - Observaciones', @TIPO=2, @ORDEN=9, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Bomba red de incendio
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-18', @NOMBRE=N'Bomba red de incendio', @ORDEN=18, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-18-1', @TEXTO=N'Bomba red de incendio (55 kW) - Filtracion', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-18-2', @TEXTO=N'Bomba red de incendio (55 kW) - Consumo', @TIPO=4, @ORDEN=2, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-18-3', @TEXTO=N'Bomba red de incendio (55 kW) - Observaciones', @TIPO=2, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Bombas de agua Riles
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-19', @NOMBRE=N'Bombas de agua Riles', @ORDEN=19, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-19-1', @TEXTO=N'Bomba 1 (0,75 kW) - Filtracion', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-19-2', @TEXTO=N'Bomba 1 (0,75 kW) - Consumo', @TIPO=4, @ORDEN=2, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-19-3', @TEXTO=N'Bomba 1 (0,75 kW) - Observaciones', @TIPO=2, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-19-4', @TEXTO=N'Bomba 2 (0,75 kW) - Filtracion', @TIPO=5, @ORDEN=4, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-19-5', @TEXTO=N'Bomba 2 (0,75 kW) - Consumo', @TIPO=4, @ORDEN=5, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-19-6', @TEXTO=N'Bomba 2 (0,75 kW) - Observaciones', @TIPO=2, @ORDEN=6, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Bombas de agua potable externa
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-20', @NOMBRE=N'Bombas de agua potable externa', @ORDEN=20, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-20-1', @TEXTO=N'Bomba agua potable externa (5,5 kW) - Filtracion', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-20-2', @TEXTO=N'Bomba agua potable externa (5,5 kW) - Consumo', @TIPO=4, @ORDEN=2, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-20-3', @TEXTO=N'Bomba agua potable externa (5,5 kW) - Observaciones', @TIPO=2, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Bomba estanque glicol
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-21', @NOMBRE=N'Bomba estanque glicol', @ORDEN=21, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-21-1', @TEXTO=N'Bomba 1 (0,75 kW) - Filtracion', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-21-2', @TEXTO=N'Bomba 1 (0,75 kW) - Consumo', @TIPO=4, @ORDEN=2, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-21-3', @TEXTO=N'Bomba 1 (0,75 kW) - Observaciones', @TIPO=2, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-21-4', @TEXTO=N'Bomba 2 (0,75 kW) - Filtracion', @TIPO=5, @ORDEN=4, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-21-5', @TEXTO=N'Bomba 2 (0,75 kW) - Consumo', @TIPO=4, @ORDEN=5, @UNIDAD=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-21-6', @TEXTO=N'Bomba 2 (0,75 kW) - Observaciones', @TIPO=2, @ORDEN=6, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Termos agua
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-22', @NOMBRE=N'Termos agua', @ORDEN=22, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-22-1', @TEXTO=N'Banos en funcionamiento', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-22-2', @TEXTO=N'Filtros sanitarios', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Sector isla
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-23', @NOMBRE=N'Sector isla', @ORDEN=23, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-23-1', @TEXTO=N'Carga de sal', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-23-2', @TEXTO=N'Nivel Cloropol', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Calderas
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-24', @NOMBRE=N'Calderas', @ORDEN=24, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-24-1', @TEXTO=N'Caldera 1 - Carga de Boropres AP', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-24-2', @TEXTO=N'Caldera 1 - Carga de Polimex 50-1', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-24-3', @TEXTO=N'Caldera 1 - Estado de dosificacion', @TIPO=5, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-24-4', @TEXTO=N'Caldera 2 - Carga de Boropres AP', @TIPO=5, @ORDEN=4, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-24-5', @TEXTO=N'Caldera 2 - Carga de Polimex 50-1', @TIPO=5, @ORDEN=5, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-24-6', @TEXTO=N'Caldera 2 - Estado de dosificacion', @TIPO=5, @ORDEN=6, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-24-7', @TEXTO=N'Caldera 3 - Carga de Boropres AP', @TIPO=5, @ORDEN=7, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-24-8', @TEXTO=N'Caldera 3 - Carga de Polimex 50-1', @TIPO=5, @ORDEN=8, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-24-9', @TEXTO=N'Caldera 3 - Estado de dosificacion', @TIPO=5, @ORDEN=9, @UNIDAD=NULL, @USUARIO=@USUARIO

-- Seccion: Rodamientos de hornos
EXEC [dbo].[INS_CHECKLIST_SECCION] @ID=@SEC OUTPUT, @VERSION=@VERSION, @CODIGO=N'SEC-25', @NOMBRE=N'Rodamientos de hornos', @ORDEN=25, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-1', @TEXTO=N'Horno L1 - Polin centrador entrada', @TIPO=5, @ORDEN=1, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-2', @TEXTO=N'Horno L1 - Polin conducido entrada', @TIPO=5, @ORDEN=2, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-3', @TEXTO=N'Horno L1 - Polin conducido 1 salida', @TIPO=5, @ORDEN=3, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-4', @TEXTO=N'Horno L1 - Polin conducido 2 salida', @TIPO=5, @ORDEN=4, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-5', @TEXTO=N'Horno L1 - Polin conducido 3 salida', @TIPO=5, @ORDEN=5, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-6', @TEXTO=N'Horno L1 - Polin motriz salida', @TIPO=5, @ORDEN=6, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-7', @TEXTO=N'Horno L1 - Presion y nivel central hidraulica', @TIPO=5, @ORDEN=7, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-8', @TEXTO=N'Horno L1 - Estado y funcionamiento del centrador', @TIPO=5, @ORDEN=8, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-9', @TEXTO=N'Horno L2 - Polin centrador entrada', @TIPO=5, @ORDEN=9, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-10', @TEXTO=N'Horno L2 - Polin conducido entrada', @TIPO=5, @ORDEN=10, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-11', @TEXTO=N'Horno L2 - Polin conducido 1 salida', @TIPO=5, @ORDEN=11, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-12', @TEXTO=N'Horno L2 - Polin conducido 2 salida', @TIPO=5, @ORDEN=12, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-13', @TEXTO=N'Horno L2 - Polin conducido 3 salida', @TIPO=5, @ORDEN=13, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-14', @TEXTO=N'Horno L2 - Polin motriz salida', @TIPO=5, @ORDEN=14, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-15', @TEXTO=N'Horno L2 - Presion y nivel central hidraulica', @TIPO=5, @ORDEN=15, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-16', @TEXTO=N'Horno L2 - Estado y funcionamiento del centrador', @TIPO=5, @ORDEN=16, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-17', @TEXTO=N'Horno L3 - Polin centrador entrada', @TIPO=5, @ORDEN=17, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-18', @TEXTO=N'Horno L3 - Polin conducido entrada', @TIPO=5, @ORDEN=18, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-19', @TEXTO=N'Horno L3 - Polin conducido 1 salida', @TIPO=5, @ORDEN=19, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-20', @TEXTO=N'Horno L3 - Polin conducido 2 salida', @TIPO=5, @ORDEN=20, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-21', @TEXTO=N'Horno L3 - Polin conducido 3 salida', @TIPO=5, @ORDEN=21, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-22', @TEXTO=N'Horno L3 - Polin motriz salida', @TIPO=5, @ORDEN=22, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-23', @TEXTO=N'Horno L3 - Presion y nivel central hidraulica', @TIPO=5, @ORDEN=23, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-24', @TEXTO=N'Horno L3 - Estado y funcionamiento del centrador', @TIPO=5, @ORDEN=24, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-25', @TEXTO=N'Horno L4 - Polin centrador entrada', @TIPO=5, @ORDEN=25, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-26', @TEXTO=N'Horno L4 - Polin conducido entrada', @TIPO=5, @ORDEN=26, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-27', @TEXTO=N'Horno L4 - Polin conducido 1 salida', @TIPO=5, @ORDEN=27, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-28', @TEXTO=N'Horno L4 - Polin conducido 2 salida', @TIPO=5, @ORDEN=28, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-29', @TEXTO=N'Horno L4 - Polin conducido 3 salida', @TIPO=5, @ORDEN=29, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-30', @TEXTO=N'Horno L4 - Polin motriz salida', @TIPO=5, @ORDEN=30, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-31', @TEXTO=N'Horno L4 - Presion y nivel central hidraulica', @TIPO=5, @ORDEN=31, @UNIDAD=NULL, @USUARIO=@USUARIO
EXEC [dbo].[INS_CHECKLIST_ITEM] @ID=@ITEM OUTPUT, @VERSION=@VERSION, @SECCION=@SEC, @CODIGO=N'ITM-25-32', @TEXTO=N'Horno L4 - Estado y funcionamiento del centrador', @TIPO=5, @ORDEN=32, @UNIDAD=NULL, @USUARIO=@USUARIO

SELECT @PLANTILLA AS PLANTILLA, @VERSION AS VERSION,
       (SELECT COUNT(*) FROM Checklist_Plantilla_Seccion WHERE cps_checklist_plantilla_version=@VERSION) AS SECCIONES,
       (SELECT COUNT(*) FROM Checklist_Plantilla_Item WHERE cpi_checklist_plantilla_version=@VERSION) AS ITEMS
GO
PRINT '193_SPRINT4_CHECKLIST_SOP09R24 aplicado.'
GO
