SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/* ============================================================================
   402 · Operación › Cumplimiento · 09-10-2026  (parte d)

   SEL_OPERACION_CUMPLIMIENTO mide lo programado del mes elegido (planes, inspecciones y tareas):
     «vencida» = ya pasó su límite · «hecha» = estado 4 o su OT cerrada ·
     cumplimiento = hechas / vencidas (las que aún están en plazo no cuentan).
   Se mide contra la fecha ORIGINAL cuando una ejecución se reprogramó (la reprogramada no
   «escapa»: SEL_OPERACION_EJECUCIONES excluye la ocurrencia reemplazada, queda la nueva).
   Filtros opcionales: planta, área, responsable y criticidad del activo.
   Devuelve: 0 indicadores · 1 serie de 6 meses · 2 por tipo de trabajo · 3 por plan, inspección o
   tarea (peor primero) · 4 por activo · 5 por responsable.
   Aplicar con -I. Idempotente.
   ============================================================================ */
SET NOCOUNT ON
GO
CREATE OR ALTER PROCEDURE [dbo].[SEL_OPERACION_CUMPLIMIENTO]
    @CLIENTE     INT,
    @INSTALACION INT = NULL,
    @AREA        INT = NULL,
    @RESPONSABLE INT = NULL,
    @CRITICIDAD  INT = NULL,
    @MES         DATE = NULL
AS
SET NOCOUNT ON
DECLARE @AHORA DATETIME = [dbo].[FNC_AHORA]()
DECLARE @HOY DATE = CAST(@AHORA AS DATE)
IF @MES IS NULL SET @MES = DATEADD(DAY, 1 - DAY(@HOY), @HOY)
SET @MES = DATEADD(DAY, 1 - DAY(@MES), @MES)
DECLARE @M0 DATETIME = CAST(@MES AS DATETIME), @M1 DATETIME = DATEADD(MONTH, 1, CAST(@MES AS DATETIME))
DECLARE @SERIE0 DATETIME = DATEADD(MONTH, -5, @M0)

CREATE TABLE #EJ (TIPO VARCHAR(10), ID INT, FECHA DATETIME, LIMITE DATETIME, ESTADO_ID INT, SITUACION VARCHAR(12), ACTIVO_ID INT, ACTIVO_CODIGO NVARCHAR(100), ACTIVO NVARCHAR(300), AREA NVARCHAR(200), CRITICIDAD INT,
                 TITULO NVARCHAR(300), REF NVARCHAR(60), REF_NOMBRE NVARCHAR(300), ACTIVIDADES INT, PARADA BIT, OT_ID INT, OT_NUMERO INT, OT_ESTADO INT, HALLAZGOS INT, RESPONSABLE NVARCHAR(200))
DECLARE @D DATE = @SERIE0, @H DATE = DATEADD(DAY, -1, CAST(@M1 AS DATE))
INSERT INTO #EJ EXEC [dbo].[SEL_OPERACION_EJECUCIONES] @CLIENTE = @CLIENTE, @INSTALACION = @INSTALACION, @AREA = @AREA, @RESPONSABLE = @RESPONSABLE, @CRITICIDAD = @CRITICIDAD, @DESDE = @D, @HASTA = @H
DELETE FROM #EJ WHERE SITUACION = 'CANCELADA'

/* vencida = ya pasó el límite (o la fecha, si no tiene límite); hecha = cerrada */
SELECT *, CAST(CASE WHEN ISNULL(LIMITE, FECHA) < @AHORA THEN 1 ELSE 0 END AS BIT) AS VENCIDA, CAST(CASE WHEN SITUACION = 'CERRADA' AND ESTADO_ID = 4 OR OT_ESTADO = 4 THEN 1 ELSE 0 END AS BIT) AS HECHA
INTO   #X FROM #EJ

SELECT a.act_id AS ACTIVO_ID INTO #ACT
FROM   [dbo].[Activo] a
WHERE  a.act_cliente = @CLIENTE AND a.act_habilitado = 1 AND (@INSTALACION IS NULL OR a.act_cliente_instalacion = @INSTALACION)
  AND  (@AREA IS NULL OR a.act_instalacion_area = @AREA) AND (@CRITICIDAD IS NULL OR ISNULL(a.act_criticidad_nivel, 1) = @CRITICIDAD)

SELECT o.otr_id, o.otr_orden_trabajo_estado AS ESTADO, o.otr_fecha_programada_utc AS PROGRAMADA, o.otr_fecha_creacion AS CREADA, o.otr_fecha_cierre AS CIERRE,
       ISNULL(o.otr_duracion_estimada_minuto, 0) AS DURACION, ISNULL(o.otr_duracion_real_minuto, 0) AS REAL
INTO   #OT
FROM   [dbo].[Orden_Trabajo] o JOIN #ACT a ON a.ACTIVO_ID = o.otr_activo
WHERE  o.otr_cliente = @CLIENTE AND o.otr_habilitado = 1

/* ======================= 0 · indicadores del mes ======================= */
SELECT
    PLANIFICADO  = (SELECT COUNT(*) FROM #X WHERE FECHA >= @M0 AND FECHA < @M1),
    VENCIDAS     = (SELECT COUNT(*) FROM #X WHERE FECHA >= @M0 AND FECHA < @M1 AND VENCIDA = 1),
    CUMPLIDAS    = (SELECT COUNT(*) FROM #X WHERE FECHA >= @M0 AND FECHA < @M1 AND VENCIDA = 1 AND HECHA = 1),
    EJECUTADO    = (SELECT COUNT(*) FROM #X WHERE FECHA >= @M0 AND FECHA < @M1 AND HECHA = 1),
    PENDIENTE    = (SELECT COUNT(*) FROM #X WHERE FECHA >= @M0 AND FECHA < @M1 AND HECHA = 0 AND FECHA >= @AHORA),
    ATRASADO     = (SELECT COUNT(*) FROM #X WHERE FECHA >= @M0 AND FECHA < @M1 AND HECHA = 0 AND FECHA < @AHORA AND OT_ID IS NULL),
    EN_EJECUCION = (SELECT COUNT(*) FROM #X WHERE FECHA >= @M0 AND FECHA < @M1 AND OT_ESTADO IN (2, 3)),
    OT_ABIERTAS  = (SELECT COUNT(*) FROM #OT WHERE ESTADO < 4 AND PROGRAMADA >= @M0 AND PROGRAMADA < @M1),
    OT_VENCIDAS  = (SELECT COUNT(*) FROM #OT WHERE ESTADO < 4 AND PROGRAMADA >= @M0 AND PROGRAMADA < @M1 AND PROGRAMADA < @AHORA),
    TIEMPO_PROM  = (SELECT ISNULL(AVG(DATEDIFF(MINUTE, CREADA, CIERRE)), 0) FROM #OT WHERE ESTADO = 4 AND CIERRE >= @M0 AND CIERRE < @M1),
    DURACION_MIN = (SELECT ISNULL(SUM(REAL), 0) FROM #OT WHERE ESTADO = 4 AND CIERRE >= @M0 AND CIERRE < @M1),
    BACKLOG_MIN  = (SELECT ISNULL(SUM(DURACION), 0) FROM #OT WHERE ESTADO < 4),
    AFECTADOS    = (SELECT COUNT(DISTINCT ACTIVO_ID) FROM #X WHERE FECHA >= @M0 AND FECHA < @M1 AND HECHA = 0 AND FECHA < @AHORA AND OT_ID IS NULL)

/* ======================= 1 · serie de 6 meses ======================= */
;WITH M AS (SELECT 0 AS N UNION ALL SELECT N + 1 FROM M WHERE N < 5)
SELECT CONVERT(VARCHAR(7), DATEADD(MONTH, N, @SERIE0), 120) AS MES,
       CUMPLIMIENTO = (SELECT CASE WHEN COUNT(*) = 0 THEN NULL ELSE CAST(ROUND(100.0 * SUM(CASE WHEN HECHA = 1 THEN 1 ELSE 0 END) / COUNT(*), 0) AS INT) END
                         FROM #X WHERE VENCIDA = 1 AND FECHA >= DATEADD(MONTH, N, @SERIE0) AND FECHA < DATEADD(MONTH, N + 1, @SERIE0))
FROM M ORDER BY N

/* ======================= 2 · por tipo de trabajo ======================= */
SELECT TIPO, COUNT(*) AS N, SUM(CAST(VENCIDA AS INT)) AS VENCIDAS, SUM(CASE WHEN VENCIDA = 1 AND HECHA = 1 THEN 1 ELSE 0 END) AS CUMPLIDAS
FROM   #X WHERE FECHA >= @M0 AND FECHA < @M1 GROUP BY TIPO

/* ======================= 3 · por plan, inspección o tarea ======================= */
SELECT TOP 12 TIPO, ISNULL(NULLIF(REF, N''), TITULO) AS CLAVE, MAX(CASE WHEN TIPO = 'PLAN' THEN REF_NOMBRE ELSE TITULO END) AS NOMBRE, COUNT(*) AS N,
       SUM(CAST(VENCIDA AS INT)) AS VENCIDAS, SUM(CASE WHEN VENCIDA = 1 AND HECHA = 1 THEN 1 ELSE 0 END) AS CUMPLIDAS,
       SUM(CASE WHEN HECHA = 0 AND FECHA < @AHORA AND OT_ID IS NULL THEN 1 ELSE 0 END) AS ATRASADAS
FROM   #X WHERE FECHA >= @M0 AND FECHA < @M1
GROUP BY TIPO, ISNULL(NULLIF(REF, N''), TITULO)
ORDER BY CASE WHEN SUM(CAST(VENCIDA AS INT)) = 0 THEN 1 ELSE 0 END,
         1.0 * SUM(CASE WHEN VENCIDA = 1 AND HECHA = 1 THEN 1 ELSE 0 END) / NULLIF(SUM(CAST(VENCIDA AS INT)), 0),
         SUM(CASE WHEN HECHA = 0 AND FECHA < @AHORA AND OT_ID IS NULL THEN 1 ELSE 0 END) DESC

/* ======================= 4 · por activo ======================= */
SELECT TOP 8 ACTIVO_ID, MAX(ACTIVO_CODIGO) AS CODIGO, MAX(ACTIVO) AS NOMBRE, MAX(AREA) AS AREA, MAX(CRITICIDAD) AS CRITICIDAD, COUNT(*) AS N,
       SUM(CAST(VENCIDA AS INT)) AS VENCIDAS, SUM(CASE WHEN VENCIDA = 1 AND HECHA = 1 THEN 1 ELSE 0 END) AS CUMPLIDAS,
       SUM(CASE WHEN HECHA = 0 AND FECHA < @AHORA AND OT_ID IS NULL THEN 1 ELSE 0 END) AS ATRASADAS
FROM   #X WHERE FECHA >= @M0 AND FECHA < @M1
GROUP BY ACTIVO_ID
ORDER BY CASE WHEN SUM(CAST(VENCIDA AS INT)) = 0 THEN 1 ELSE 0 END,
         1.0 * SUM(CASE WHEN VENCIDA = 1 AND HECHA = 1 THEN 1 ELSE 0 END) / NULLIF(SUM(CAST(VENCIDA AS INT)), 0)

/* ======================= 5 · por responsable ======================= */
SELECT RESPONSABLE, COUNT(*) AS N, SUM(CAST(VENCIDA AS INT)) AS VENCIDAS, SUM(CASE WHEN VENCIDA = 1 AND HECHA = 1 THEN 1 ELSE 0 END) AS CUMPLIDAS,
       SUM(CASE WHEN HECHA = 0 AND FECHA < @AHORA AND OT_ID IS NULL THEN 1 ELSE 0 END) AS ATRASADAS
FROM   #X WHERE FECHA >= @M0 AND FECHA < @M1 AND RESPONSABLE <> N''
GROUP BY RESPONSABLE
ORDER BY CASE WHEN SUM(CAST(VENCIDA AS INT)) = 0 THEN 1 ELSE 0 END, 1.0 * SUM(CASE WHEN VENCIDA = 1 AND HECHA = 1 THEN 1 ELSE 0 END) / NULLIF(SUM(CAST(VENCIDA AS INT)), 0)
RETURN 0
GO
PRINT '402_OPERACION_CUMPLIMIENTO aplicado.'
GO
